### ISSUE TITLE
script breaks with big files

### ISSUE THREAD

**Issue by dewiestr** [SekoiaLab/Fastir_Collector_Linux#7]
I have a large file in tmp (8Gb) , which breaks the script: 

Traceback (most recent call last):
  File "/mnt/raid/tools/Fastir_Collector_Linux/fastIR_collector_linux.py", line 669, in <module>
    main()
  File "/mnt/raid/tools/Fastir_Collector_Linux/fastIR_collector_linux.py", line 661, in main
    f.execute()
  File "/mnt/raid/tools/Fastir_Collector_Linux/fastIR_collector_linux.py", line 531, in execute
    getattr(c, attr)()
  File "/mnt/raid/tools/Fastir_Collector_Linux/fastIR_collector_linux.py", line 410, in get_temp
    utils.zip_file(file_to_zip, 'tmp.zip', self.args['output_dir'], self.args['logger'])
  File "/mnt/raid/tools/Fastir_Collector_Linux/fastIR_collector_linux.py", line 143, in zip_file
    logger.error(e.strerror + ' ' + path)
AttributeError: 'LargeZipFile' object has no attribute 'strerror'

This is on an Ubuntu 14.04.

**Comment by SyBen** [comment]
Hey, would you mind trying this version before I merge it ? https://github.com/SekoiaLab/Fastir_Collector_Linux/blob/zip_large_files/fastIR_collector_linux.py
Thanks 🙂
